apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-math-demo
  labels:
    app: dice-math-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-math-demo
  template:
    metadata:
      labels:
        app: dice-math-demo
    spec:
      containers:
        - name: dice-math-demo
          image: registry.gitlab.com/fullpipe/registry/dice-math-demo:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
      imagePullSecrets:
        - name: gitlab-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dice-math-demo
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: dice-math-demo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dice-math-demo
spec:
  ingressClassName: 'traefik'
  tls:
    - hosts:
        - dice-math.fullpipe.dev
      secretName: dice-math.fullpipe.dev-tls
  rules:
    - host: dice-math.fullpipe.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dice-math-demo
                port:
                  name: http
